name: Update Covers Index

on:
  push:
    paths:
      - 'resources/covers/compressed/**'
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Covers Index
        run: |
          ls -1 resources/covers/compressed/*.JPG | awk -F'/' '{print $NF}' | sed 's/\.JPG//g' > resources/covers/index.tsv
          
      - name: Commit and Push
        run: |
          git config --global user.name "PS3-Pro Bot"
          git config --global user.email "bot@ps3pro.com"
          git add resources/covers/index.tsv
          git commit -m "Auto-update: Covers index" || echo "No changes to commit"
          git push